<div class="whatsapp">
    <p><a title="Atendimento" href="https://api.whatsapp.com/send?phone=5553999566761&amp;text=Oieee!!%20Nosso%20atendimento%20via%20WhatsApp%20%C3%A9%20de%20segunda%20%C3%A0%20sexta%2C%20das%208h%20as%2017h.%20Como%20podemos%20lhe%20ajudar%3F" target="_blank" rel="noopener">
            <img src="<?php echo $this->getViewFileUrl('Innovatis_WhatsappFooter::images/whatsapp_img.png'); ?>"

            alt="" width="80" height="100"/>
        </a></p>
</div>
