<div class="baskets text-center">
    <h2>Conheça nossas Cestas</h2>
    <p>Monte sua cesta com produtos orgânicos, frescos e entregue na sua casa.</p>
    <p>Com três opções de tamanho Grande (12 produtos), Média (8 produtos) e pequena (5 produtos), escolha a sua:</p>

    <div class="row baskets-img">
        <div class="col-md-4">
            <img src="<?php echo $block->getViewFileUrl('images/basket_small.jpg'); ?>" title="Cesta Pequena" alt="Cesta Pequena">
        </div>
        <div class="col-md-4">
            <img src="<?php echo $block->getViewFileUrl('images/basket_medium.jpg'); ?>" title="Cesta Média" alt="Cesta Média">
        </div>
        <div class="col-md-4">
            <img src="<?php echo $block->getViewFileUrl('images/basket_big.jpg'); ?>" title="Cesta Grande" alt="Cesta Grande">
        </div>
    </div>
</div>
